/* 
 * V2000 UA phone firmware for x51
 * made in 3 month by 19yo student in Ukraine at early 2000
 * Victor Kozub (C) Copyright 2000
 * https://github.com/xen1024
 */

;	- DEFMT.INC -
;
; Include file for creating a tiny model library
;
; Version: 4.00 [IANR]
;
local_DATA	DEFINE		1
local_IDATA	DEFINE		0
local_XDATA	DEFINE		0
global_DATA	DEFINE		1
global_IDATA	DEFINE		0
global_XDATA	DEFINE		0
banked_mode	DEFINE		0
		LSTCND		+

